const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const kit = path.resolve(__dirname, '..');
(async () => {
  await fs.mkdir(path.join(kit, 'reports/test-artifacts'), {recursive: true});
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  try {
    const page = await browser.newPage({viewport: {width: 1600, height: 1000}}), errors = [], checks = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(pathToFileURL(path.join(kit, 'dist/blueprint_editor.html')).href);
    await page.evaluate(() => BlueprintEditor.ready);
    const sample = JSON.parse(await fs.readFile(path.join(kit, 'examples/demo_blueprint.json'), 'utf8'));
    await page.evaluate(d => BlueprintEditor.importLayout(d), sample);
    await page.locator('#btnGamePreview').click();
    await page.waitForFunction(() => document.getElementById('presentationCanvas').width === 1920);
    assert((await page.locator('#presentationAuto').textContent()).includes('23×14'));
    const inventory = await page.evaluate(() => BlueprintPresentation.inventory(data));
    assert.equal(inventory.find(i => i.id === 'item_port_furnance_1').count, 2);
    assert.equal(inventory.find(i => i.id === 'item_log_belt_01').count, 0);
    assert.equal(inventory.find(i => i.id === 'item_log_splitter').count, 0);
    assert(inventory.every((i, n) => !n || inventory[n - 1].sortId1 >= i.sortId1));
    assert.equal(inventory.at(-1).id, 'item_log_belt_01');
    checks.push('legacy layouts generate actual occupied size and sorted native inventory; logistics hide counts');
    await page.locator('#presentationName').fill('通用息壤装备');
    await page.locator('#presentationCreator').fill('1000000001');
    await page.locator('#presentationTags').fill('装备，武陵');
    await page.locator('#btnChooseCover').click();
    await page.locator('#coverSearch').fill('item_iron_nugget');
    await page.locator('[data-cover="item_iron_nugget"]').click();
    await page.locator('[data-cover-color="green"]').click();
    await page.waitForFunction(() => document.getElementById('presentationCoverName').textContent === '蓝铁块');
    await page.locator('#btnApplyPresentation').click();
    const saved = await page.evaluate(() => BlueprintEditor.getData());
    assert.equal(saved.presentation.creatorId, '1000000001');
    assert.deepEqual(saved.presentation.tags, ['装备', '武陵']);
    assert.equal(saved.presentation.coverColor, 'green');
    assert.equal(saved.presentation.coverId, 'item_iron_nugget');
    await page.locator('#btnUndo').click(); assert.equal(await page.evaluate(() => data.presentation), undefined);
    await page.locator('#btnRedo').click(); assert.equal(await page.evaluate(() => data.presentation.creatorId), '1000000001');
    checks.push('editable name, creator, tags, raw cover and native paper color apply and undo/redo as one change');
    await page.evaluate(() => saveNow()); await page.reload(); await page.evaluate(() => BlueprintEditor.ready);
    assert.deepEqual(await page.evaluate(() => BlueprintEditor.getData()), saved);
    checks.push('presentation metadata survives local autosave/reload and remains part of layout JSON');
    await page.locator('#btnGamePreview').click();
    await page.locator('#presentationCreator').fill('cancelled');
    await page.locator('#btnChooseCover').focus(); await page.keyboard.press('Delete'); await page.keyboard.press('r');
    await page.keyboard.press('Escape');
    assert.deepEqual(await page.evaluate(() => BlueprintEditor.getData()), saved);
    checks.push('cancel and modal keyboard shortcuts leave layout and saved details untouched');
    await page.locator('#btnGamePreview').click();
    const downloadPromise = page.waitForEvent('download'); await page.locator('#btnExportPresentation').click();
    const download = await downloadPromise;
    assert(download.suggestedFilename().endsWith('_蓝图预览.png'));
    await download.saveAs(path.join(kit, 'reports/test-artifacts/blueprint_full_preview.png'));
    await page.screenshot({path: path.join(kit, 'reports/test-artifacts/blueprint_details_editor.png')});
    await fs.writeFile(path.join(kit, 'reports/test-artifacts/blueprint_full_preview.json'), JSON.stringify(saved, null, 2));
    const pixels = await page.evaluate(async () => {
      const a = await BlueprintEditor.exportPreview(data), b = await BlueprintEditor.exportPreview({...data, presentation: {...data.presentation, creatorId: '9999999999'}});
      const aa = a.getContext('2d').getImageData(0, 0, a.width, a.height).data, bb = b.getContext('2d').getImageData(0, 0, b.width, b.height).data;
      let left = 0, right = 0;
      for (let i = 0; i < aa.length; i += 4) if (aa[i] !== bb[i] || aa[i + 1] !== bb[i + 1] || aa[i + 2] !== bb[i + 2]) (i / 4 % a.width < 1908) ? left++ : right++;
      return {width: a.width, height: a.height, left, right, alpha: aa[3]};
    });
    assert.equal(pixels.width, 2560); assert.equal(pixels.height, 1440); assert.equal(pixels.left, 0); assert(pixels.right > 100); assert.equal(pixels.alpha, 255);
    checks.push('real full PNG download is 2560×1440; creator text changes the exported right panel only');
    await page.locator('#presentationDescription').fill('详细说明。'.repeat(60));
    await page.locator('#presentationTags').fill('一，二，三，四，五，六，七');
    await page.locator('#btnApplyPresentation').click(); assert(await page.locator('#presentationDialog').isVisible());
    assert((await page.locator('#presentationError').textContent()).includes('6'));
    await page.locator('#presentationTags').fill('装备，武陵');
    const long = await page.evaluate(async () => {
      const layout = BlueprintEditor.getData(); layout.presentation.description = '完整保留长文本内容。'.repeat(35);
      const a = await BlueprintEditor.exportPreview(layout, 1920), m = BlueprintPresentation.metrics(layout);
      return {height: a.height, min: Math.ceil((m.listY + Math.ceil(m.items.length / 4) * 143) * .75)};
    });
    assert(long.height >= long.min);
    checks.push('invalid metadata cannot apply; long descriptions extend the export without clipping inventory');
    const fallback = await page.evaluate(async () => {
      const layout = BlueprintEditor.getData(); layout.presentation = {creatorId: null, tags: null, description: null, coverId: 'constructor'};
      const out = await BlueprintEditor.exportPreview(layout, 1920); return {width: out.width, coverId: layout.presentation.coverId};
    });
    assert.equal(fallback.width, 1920); assert.equal(fallback.coverId, 'constructor');
    checks.push('optional null fields and unknown imported cover IDs render safely without rewriting the source ID');
    await page.locator('#btnCancelPresentation').click();
    await page.setViewportSize({width: 660, height: 900}); await page.locator('#btnGamePreview').click();
    await page.locator('#presentationCreator').scrollIntoViewIfNeeded(); await page.locator('#presentationCreator').fill('123');
    const box = await page.locator('#presentationCreator').boundingBox(); assert(box.x >= 0 && box.x + box.width <= 660);
    await page.locator('#btnApplyPresentation').click(); assert.equal(await page.evaluate(() => data.presentation.creatorId), '123');
    checks.push('narrow-window presentation settings remain reachable and editable');
    assert.deepEqual(errors, []);
    await fs.writeFile(path.join(kit, 'reports/test-artifacts/presentation_verification.json'), JSON.stringify({checks, pixels, errors}, null, 2));
    console.log(JSON.stringify({passed: checks.length, checks, pixels, errors}, null, 2));
  } finally { await browser.close(); }
})().catch(e => {console.error(e); process.exitCode = 1;});
